# configs/example.yaml

output:
  root_dir: "pipeline/deg_fetcher"
  batch_identifier: "batch_20250130"

# Ceroni et al. (DOI: 10.1038/nmeth.4635)
ceroni:
  data:
    dataset_key: "ceroni"
    sheet_name: "Mean FPKM"
    usecols: "A:P"
    header: 0
    skiprows: 3

  thresholds:
    log2_fc_threshold: 2.5
    time_point: 15
    drop_zeros: true
    plasmid_pairs:
      - [ "pLys-M1", "pLys" ]
      - [ "pPD864-LacZ", "pPD864" ]
      - [ "pSB1C3-H3", "pSB1C3" ]

  output:
    csv_subdir: "csv"
    plot_subdir: "plots"

mori:
  data:
    dataset_key: "mori_ev8"
    sheet_name: "EV8-AbsoluteMassFractions-1"
    usecols:
      - "Gene name"
      - "Lib-02"
      - "Lib-06"
      - "Lib-14"
      - "Lib-17"
      - "Lib-19"
      - "Lib-20"
      - "Lib-28"

  comparisons:
    - { condition: "Lib-17", reference: "Lib-20" }
    - { condition: "Lib-02", reference: "Lib-20" }
    - { condition: "Lib-06", reference: "Lib-20" }
    - { condition: "Lib-14", reference: "Lib-20" }
    - { condition: "Lib-19", reference: "Lib-20" }
    - { condition: "Lib-28", reference: "Lib-20" }
    - { condition: "Lib-19", reference: "Lib-20" }

  descriptors:
    "Lib-00-A1": "Glucose minimal medium (A1-1)"
    "Lib-02": "High osmolarity"
    "Lib-06": "Poor carbon (acetate)"
    "Lib-14": "Oxidative stress"
    "Lib-17": "Low pH (acetate)"
    "Lib-19": "LB stationary"
    "Lib-20": "LB log-phase"
    "Lib-28": "Xylose + oxaloacetate"

  thresholds:
    log2_fc_threshold: 2.5

  output:
    csv_subdir: "csv"
    plot_subdir: "plots"

# Wu et al (DOI: 10.1038/s41564-022-01310-w)
wu:
  data:
    dataset_key: "wu"
    sheet_name: "Group #1 protein mass fractions"

  thresholds:
    log2_fc_threshold: 2.5
    comparisons:
      Clim_MOPS_Over_Rich_MOPS: ["M1", "N5"]
      Clim_MOPS_Over_WT_Rich_LB: ["M1", "O8"]

  output:
    csv_subdir: "csv"
    plot_subdir: "plots"

# Zhu et al. (DOI: 10.1038/s41467-023-36254-0)
zhu:
  data:
    dataset_key: "zhu"
    sheet_name: "supplementary data 2"
    usecols: "B,C,I,K"
    header: 0

  thresholds:
    log2_fc_threshold: 5

  output:
    csv_subdir: "csv"
    plot_subdir: "plots"

# Emani et al (DOI: 10.1093/synbio/ysad013)
emani:
  data:
    dataset_key: "emani"
    sheet_name: "Figure 5_alltags v control"
    usecols:
      - "Gene"
      - "log2FoldChange (Green = Upregulated in 10uM IPTG All Tags)"
      - "pvalue"
      - "padj"
  thresholds:
    log2_fc_threshold: 2.0
  output:
    csv_subdir: "csv"
    plot_subdir: "plots"

# Schmidt et al. (DOI: 10.1038/nbt.3418)
schmidt:
  data:
    dataset_key: "schmidt"
    sheet_name: "Schmidt et al."
    usecols: "C:AC"
    header: 2
  thresholds:
    log2_fc_threshold: 2.5
    comparisons:
      Acetate_vs_Glucose: ["Acetate", "Glucose"]
      Xylose_vs_Glucose: ["Xylose", "Glucose"]
      Chemostat_slow_vs_fast: ["Chemostat µ=0.20", "Chemostat µ=0.5"]
      Osmotic_stress_glucose_vs_Glucose: ["Osmotic-stress glucose", "Glucose"]
  output:
    csv_subdir: "csv"
    plot_subdir: "plots"

# Radzikowski et al. (DOI: 10.15252/msb.20166998)
radzikowski:
  data:
    dataset_key: "radzikowski"
    sheet_name: "Sheet1"
    usecols: "A:S"
    header: 2
  thresholds:
    log2_fc_threshold: 2.0
    comparisons:
      Persisters_0.5h_Over_GlucoseGrowth: ["Persisters_0.5h", "GlucoseGrowth"]
      Starved_0.5h_Over_GlucoseGrowth: ["Starved_0.5h", "GlucoseGrowth"]
  output:
    csv_subdir: "csv"
    plot_subdir: "plots"

# Bie et al. (DOI: 10.1128/spectrum.00317-23)
bie:
  data:
    dataset_key: "bie"
    sheet_name: "Sheet1"
    header: 1
    usecols:
      - "Genename"
      - "KAN_readcount(KANvsH2O)"
      - "H2O_readcount(KANvsH2O)"
      - "log2FoldChange(KANvsH2O)"
      - "pval(KANvsH2O)"
      - "padj(KANvsH2O)"
      - "significant(KANvsH2O)"
      - "CIP_readcount(CIPvsH2O)"
      - "H2O_readcount(CIPvsH2O)"
      - "log2FoldChange(CIPvsH2O)"
      - "pval(CIPvsH2O)"
      - "padj(CIPvsH2O)"
      - "significant(CIPvsH2O)"

  thresholds:
    log2_fc_threshold: 5
    conditions:
      - {
          antibiotic_name: "KAN",
          gene_col: "Genename",
          abx_readcount_col: "KAN_readcount(KANvsH2O)",
          h2o_readcount_col: "H2O_readcount(KANvsH2O)",
          log2_fc_col: "log2FoldChange(KANvsH2O)",
          sig_col: "significant(KANvsH2O)"
        }
      - {
          antibiotic_name: "CIP",
          gene_col: "Genename",
          abx_readcount_col: "CIP_readcount(CIPvsH2O)",
          h2o_readcount_col: "H2O_readcount(CIPvsH2O)",
          log2_fc_col: "log2FoldChange(CIPvsH2O)",
          sig_col: "significant(CIPvsH2O)"
        }

  output:
    csv_subdir: "csv"
    plot_subdir: "plots"

deter:
  data:
    dataset_key: "deter"
    header: 0
    usecols:
      - "Name"
      - "gene"
      - "Stationary rep1"
      - "Stationary rep2"
      - "Stationary rep3"
      - "3h fresh media rep1"
      - "3h fresh media rep2"
      - "3h fresh media rep3"
      - "3h amp media rep1"
      - "3h amp media rep2"
      - "3h amp media rep3"

  thresholds:
    log2_fc_threshold: 2.0

    # Define two comparisons:
    #  1) 3h amp media vs 3h fresh media
    #  2) Stationary vs 3h fresh media
    comparisons:
      - { target: "3h amp media", reference: "3h fresh media" }
      # - { target: "Stationary", reference: "3h fresh media" }

  output:
    csv_subdir: "csv"
    plot_subdir: "plots"

jovanovic:
  data:
    dataset_key: "jovanovic"
    sheet_name: "Sheet1"
    usecols:
      - "Gene"
      - "Product"
      - "Fold regulation"
    header: 2

  thresholds:
    # Name of the column that has linear fold regulation
    fc_col: "Fold regulation"
  output:
    csv_subdir: "csv"
    plot_subdir: "plots"

rajacharya:
  data:
    dataset_key: "rajacharya"
    sheet_name: "Sheet 1"
    # columns U, V, W, X => "Accession", "genes", "logFC", "PValue"
    usecols:
      - "Accession"
      - "genes"
      - "logFC"
      - "PValue"
    header: 3

  thresholds:
    log2_fc_threshold: 2.5

  output:
    csv_subdir: "csv"
    plot_subdir: "plots"


