# configs/example.yaml
pipeline:
  name: "default"
  stages:
    degfetcher:
      root_dir: "pipeline/degfetcher"
      batch_id: "degbatch_20250630"
      modules:
        - bie
        - emani

    tffetcher:
      root_dir: "pipeline/tffetcher"
      batch_id: "tfbatch_20250630"
      input:
        deg_batch_id: "degbatch_20250630"             
        deg_csv_subdir: "csvs"
        deg_csv_groups:
          ciprofloxacin_up_bie_et_al:                    
            files:
              - { file: "bie_upregulated_degs.csv", comparison: "CIPvsH2O" }
            plot_name: "Ciprofloxacin, ↑ DEGs (Bie et al.)"       
          secretion_tag_up_emani_et_al:                    
            files:
              - { file: "emani_upregulated_degs.csv", comparison: "all_tags_vs_control" }
            plot_name: "Secretion Tag  OE, ↑ DEGs (Emani et al.)"    
        filter_gene_networks: false
        filter_gene_network_csv: "treitz_schmidt_merged.csv"
      sources:
        regulatory_networks:
          ecocyc:
            path: "ecocyc_28_reg_network"           
            enabled: true
            parser: "ecocyc_network_v28-5"
          regulondb:
            path: "regulondb_13_network_interactions"
            enabled: true
            parser: "regulondb_network_regulator_genes_v13"
      params:
        network_strategy: "union"
        include_master_regulators: true
        include_sigma_factors: true
        fdr_threshold: 0.10
        top_n: 100

    tfbsfetcher:
      root_dir: "pipeline/tfbsfetcher"
      batch_id: "tfbsbatch_20250630"
      input:
        tf_batch_id: "tfbatch_20250630"
      use_only_enriched_tfs: true
      sources:
        binding_sites:
          ecocyc:
            path: "ecocyc_28_tfbs_smart_table"
            ecocyc_motifs: true
          regdb:
            path: "regulondb_13_tf_ri_set"
            regulondb_pssm: false
      params:
        top_n: 100
      apply_jaccard_filter: true
      kmer_size: 8
      jaccard_similarity_threshold: 0.5
      selected_tf: "lexa"
      umap_n_neighbors: 15
      umap_min_dist: 0.1
      umap_figsize: [8, 6]
      umap_alpha: 0.5
      umap_dpi: 500

analysis:
  tfbsfetcher_dir: "pipeline/tfbsfetcher"
  plot_output_dir: "analysis/plots"
  csv_output_dir: "analysis/data"

  # Flag for switching between multi-comparison and single-batch analysis
  multi_comparison: false
  reference_set: "tfbsbatch_20250630"
  comparisons:
    - ["tfbsbatch_20250630", "tfbsbatch_20250630"]
  
  exclude_intersections: false
  include_unassigned: false
  umap_n_neighbors: 15
  umap_min_dist: 0.1
  umap_figsize: [8, 6]
  umap_alpha: 0.5
  umap_dpi: 150
  umap_hue: "sample"

datasets:
  # Bie et al. (DOI: 10.1128/spectrum.00317-23)
  bie:
    data:
      dataset_key: "bie"
      sheet_name: "Sheet1"
      header: 1
      usecols:
        - "Genename"
        - "KAN_readcount(KANvsH2O)"
        - "H2O_readcount(KANvsH2O)"
        - "log2FoldChange(KANvsH2O)"
        - "pval(KANvsH2O)"
        - "padj(KANvsH2O)"
        - "significant(KANvsH2O)"
        - "CIP_readcount(CIPvsH2O)"
        - "H2O_readcount(CIPvsH2O)"
        - "log2FoldChange(CIPvsH2O)"
        - "pval(CIPvsH2O)"
        - "padj(CIPvsH2O)"
        - "significant(CIPvsH2O)"

    thresholds:
      log2_fc_threshold: 5
      conditions:
        - {
            antibiotic_name: "KAN",
            gene_col: "Genename",
            abx_readcount_col: "KAN_readcount(KANvsH2O)",
            h2o_readcount_col: "H2O_readcount(KANvsH2O)",
            log2_fc_col: "log2FoldChange(KANvsH2O)",
            sig_col: "significant(KANvsH2O)"
          }
        - {
            antibiotic_name: "CIP",
            gene_col: "Genename",
            abx_readcount_col: "CIP_readcount(CIPvsH2O)",
            h2o_readcount_col: "H2O_readcount(CIPvsH2O)",
            log2_fc_col: "log2FoldChange(CIPvsH2O)",
            sig_col: "significant(CIPvsH2O)"
          }

    output:
      csv_subdir: "csvs"
      plot_subdir: "plots"

  # Emani et al (DOI: 10.1093/synbio/ysad013)
  emani:
    data:
      dataset_key: "emani"
      sheet_name: "Figure 5_alltags v control"
      usecols:
        - "Gene"
        - "log2FoldChange (Green = Upregulated in 10uM IPTG All Tags)"
        - "pvalue"
        - "padj"
    thresholds:
      log2_fc_threshold: 2.0
    output:
      csv_subdir: "csvs"
      plot_subdir: "plots"